using Product.Core.DbStructs;
using SharedLiberary.General;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Product.Core.Models.ProdSch
{
    /// <summary>
    /// when we enter data in this table it will be generate data in fullname table
    /// </summary>
    [Table(GoodTables.PropertyValue, Schema = SchemaNames.GoodSchema)]
    public class PropValue : GeneralRegister
    {
        [Key]
        public string PropValID { get; set; }
        [Required, ForeignKey(GoodTables.BaseProduct)]
        public string ProdID { get; set; }
        [Required, ForeignKey(GoodTables.Properties)]
        public string PropID { get; set; }
        /// <summary>
        /// unique
        /// </summary>
        [Required, StringLength(10)]
        public string ProprityValue { get; set; }
        /// <summary>
        /// the code will generated by the (product and property) and this code is unique and so decimal --unique
        /// </summary>
        [Required, StringLength(2)]
        public string ValCode { get; set; }
        /// <summary>
        /// group every product with special properties, (unique)   
        /// </summary>
        [Required, StringLength(15)]
        public string PackgeName { get; set; }

        public Products ProductTBL { get; set; }
        public Property PropertyTBL { get; set; }
    }
}
